version: 0.2
eb_codebuild_settings:
  CodeBuildServiceRole: arn:aws:iam::318364255844:role/service-role/codebuild-nextjs-mongodb-app-service-role
  ComputeType: t2-small
  Image: 318364255844.dkr.ecr.us-east-1.amazonaws.com/memepact
  Timeout: 20
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Installing NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - package.json
    - .next/*
